// Decompiled with JetBrains decompiler
// Type: MavLinkNet.UasRadioStatus
// Assembly: mavlink, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 89C080C4-B46E-410C-A3FD-D5B3CAF0EF8F
// Assembly location: C:\Program Files (x86)\TyphoonHGUI\myDLL\mavlink.dll

using System.IO;

#nullable disable
namespace MavLinkNet;

public class UasRadioStatus : UasMessage
{
  private ushort mRxerrors;
  private ushort mFixed;
  private byte mRssi;
  private byte mRemrssi;
  private byte mTxbuf;
  private byte mNoise;
  private byte mRemnoise;

  public ushort Rxerrors
  {
    get => this.mRxerrors;
    set
    {
      this.mRxerrors = value;
      this.NotifyUpdated();
    }
  }

  public ushort Fixed
  {
    get => this.mFixed;
    set
    {
      this.mFixed = value;
      this.NotifyUpdated();
    }
  }

  public byte Rssi
  {
    get => this.mRssi;
    set
    {
      this.mRssi = value;
      this.NotifyUpdated();
    }
  }

  public byte Remrssi
  {
    get => this.mRemrssi;
    set
    {
      this.mRemrssi = value;
      this.NotifyUpdated();
    }
  }

  public byte Txbuf
  {
    get => this.mTxbuf;
    set
    {
      this.mTxbuf = value;
      this.NotifyUpdated();
    }
  }

  public byte Noise
  {
    get => this.mNoise;
    set
    {
      this.mNoise = value;
      this.NotifyUpdated();
    }
  }

  public byte Remnoise
  {
    get => this.mRemnoise;
    set
    {
      this.mRemnoise = value;
      this.NotifyUpdated();
    }
  }

  public UasRadioStatus()
  {
    this.mMessageId = (byte) 109;
    this.CrcExtra = (byte) 185;
  }

  internal override void SerializeBody(BinaryWriter s)
  {
    s.Write(this.mRxerrors);
    s.Write(this.mFixed);
    s.Write(this.mRssi);
    s.Write(this.mRemrssi);
    s.Write(this.mTxbuf);
    s.Write(this.mNoise);
    s.Write(this.mRemnoise);
  }

  internal override void DeserializeBody(BinaryReader s)
  {
    this.mRxerrors = s.ReadUInt16();
    this.mFixed = s.ReadUInt16();
    this.mRssi = s.ReadByte();
    this.mRemrssi = s.ReadByte();
    this.mTxbuf = s.ReadByte();
    this.mNoise = s.ReadByte();
    this.mRemnoise = s.ReadByte();
  }

  protected override void InitMetadata()
  {
    this.mMetadata = new UasMessageMetadata()
    {
      Description = "Status generated by radio"
    };
    this.mMetadata.Fields.Add(new UasFieldMetadata()
    {
      Name = "Rxerrors",
      Description = "receive errors",
      NumElements = 1
    });
    this.mMetadata.Fields.Add(new UasFieldMetadata()
    {
      Name = "Fixed",
      Description = "count of error corrected packets",
      NumElements = 1
    });
    this.mMetadata.Fields.Add(new UasFieldMetadata()
    {
      Name = "Rssi",
      Description = "local signal strength",
      NumElements = 1
    });
    this.mMetadata.Fields.Add(new UasFieldMetadata()
    {
      Name = "Remrssi",
      Description = "remote signal strength",
      NumElements = 1
    });
    this.mMetadata.Fields.Add(new UasFieldMetadata()
    {
      Name = "Txbuf",
      Description = "how full the tx buffer is as a percentage",
      NumElements = 1
    });
    this.mMetadata.Fields.Add(new UasFieldMetadata()
    {
      Name = "Noise",
      Description = "background noise level",
      NumElements = 1
    });
    this.mMetadata.Fields.Add(new UasFieldMetadata()
    {
      Name = "Remnoise",
      Description = "remote background noise level",
      NumElements = 1
    });
  }
}
